packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@node-rs/argon2"
  - "embedded-postgres"
  - "@embedded-postgres/windows-x64"
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/darwin-x64"
  - "esbuild"
  - "sharp"
  - "@tailwindcss/oxide"
  - "unrs-resolver"
